#!/usr/bin/env bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${CWD}/log.sh"

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 message command <arguments>"
  exception "Need the message as first arg with command"
fi

text="$1"
shift

log::info "► running: $text"

"$@"
exit_code="$?"

if [ $exit_code -eq 0 ]; then
  log::ok "✓ $text finished"
else
  err "✗ $text failed"
fi

exit $exit_code